/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    EfficacySlider: typeof import('./src/components/chat/EfficacySlider.vue')['default']
    MessageBubble: typeof import('./src/components/chat/MessageBubble.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabBar: typeof import('./src/components/common/TabBar.vue')['default']
    TaskCard: typeof import('./src/components/chat/TaskCard.vue')['default']
  }
}
